qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 1 10
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 11 20
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 21 30
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 31 40
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 41 50
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 51 60
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 61 70
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 71 80
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 81 90
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 91 100
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 101 110
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 111 120
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 121 130
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 131 140
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 141 150
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 151 160
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 161 170
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 171 180
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 181 190
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 191 200
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 201 210
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 211 220
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 221 230
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 231 240
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 241 250
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 251 260
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 261 270
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 271 280
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 281 290
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 291 300
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 301 310
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 311 320
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 321 330
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 331 340
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 341 350
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 351 360
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 361 370
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 371 380
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 381 390
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 391 400
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 401 410
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 411 420
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 421 430
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 431 440
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 441 450
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 451 460
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 461 470
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 471 480
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 481 490
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 491 500
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 501 510
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 511 520
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 521 530
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 531 540
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 541 550
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 551 560
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 561 570
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 571 580
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 581 590
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 591 600
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 601 610
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 611 620
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 621 630
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 631 640
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 641 650
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 651 660
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 661 670
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 671 680
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 681 690
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 691 700
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 701 710
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 711 720
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 721 730
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 731 740
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 741 750
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 751 760
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 761 770
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 771 780
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 781 790
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 791 800
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 801 810
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 811 820
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 821 830
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 831 840
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 841 850
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 851 860
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 861 870
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 871 880
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 881 890
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 891 900
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 901 910
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 911 920
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 921 930
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 931 940
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 941 950
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 951 960
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 961 970
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 971 980
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 981 990
qsub -pe localslots 4 -e /dev/null -o /dev/null /net/per610a/export/das11f/ledduy/plsang/nvtiep/INS/code/sge_script/rerank_dpm.sgejob.sh 991 999
