qsub -pe localslots 6 -e /dev/null -o /dev/null /net/per900c/raid0/ledduy/github-projects/kaori-ins2014/nmduc/train_dpm_models_job.sh 9069
qsub -pe localslots 6 -e /dev/null -o /dev/null /net/per900c/raid0/ledduy/github-projects/kaori-ins2014/nmduc/train_dpm_models_job.sh 9070
qsub -pe localslots 6 -e /dev/null -o /dev/null /net/per900c/raid0/ledduy/github-projects/kaori-ins2014/nmduc/train_dpm_models_job.sh 9071
qsub -pe localslots 6 -e /dev/null -o /dev/null /net/per900c/raid0/ledduy/github-projects/kaori-ins2014/nmduc/train_dpm_models_job.sh 9072
qsub -pe localslots 6 -e /dev/null -o /dev/null /net/per900c/raid0/ledduy/github-projects/kaori-ins2014/nmduc/train_dpm_models_job.sh 9073
qsub -pe localslots 6 -e /dev/null -o /dev/null /net/per900c/raid0/ledduy/github-projects/kaori-ins2014/nmduc/train_dpm_models_job.sh 9074
qsub -pe localslots 6 -e /dev/null -o /dev/null /net/per900c/raid0/ledduy/github-projects/kaori-ins2014/nmduc/train_dpm_models_job.sh 9075
qsub -pe localslots 6 -e /dev/null -o /dev/null /net/per900c/raid0/ledduy/github-projects/kaori-ins2014/nmduc/train_dpm_models_job.sh 9076
qsub -pe localslots 6 -e /dev/null -o /dev/null /net/per900c/raid0/ledduy/github-projects/kaori-ins2014/nmduc/train_dpm_models_job.sh 9077
qsub -pe localslots 6 -e /dev/null -o /dev/null /net/per900c/raid0/ledduy/github-projects/kaori-ins2014/nmduc/train_dpm_models_job.sh 9078
qsub -pe localslots 6 -e /dev/null -o /dev/null /net/per900c/raid0/ledduy/github-projects/kaori-ins2014/nmduc/train_dpm_models_job.sh 9079
qsub -pe localslots 6 -e /dev/null -o /dev/null /net/per900c/raid0/ledduy/github-projects/kaori-ins2014/nmduc/train_dpm_models_job.sh 9080
qsub -pe localslots 6 -e /dev/null -o /dev/null /net/per900c/raid0/ledduy/github-projects/kaori-ins2014/nmduc/train_dpm_models_job.sh 9081
qsub -pe localslots 6 -e /dev/null -o /dev/null /net/per900c/raid0/ledduy/github-projects/kaori-ins2014/nmduc/train_dpm_models_job.sh 9082
qsub -pe localslots 6 -e /dev/null -o /dev/null /net/per900c/raid0/ledduy/github-projects/kaori-ins2014/nmduc/train_dpm_models_job.sh 9083
qsub -pe localslots 6 -e /dev/null -o /dev/null /net/per900c/raid0/ledduy/github-projects/kaori-ins2014/nmduc/train_dpm_models_job.sh 9084
qsub -pe localslots 6 -e /dev/null -o /dev/null /net/per900c/raid0/ledduy/github-projects/kaori-ins2014/nmduc/train_dpm_models_job.sh 9085
qsub -pe localslots 6 -e /dev/null -o /dev/null /net/per900c/raid0/ledduy/github-projects/kaori-ins2014/nmduc/train_dpm_models_job.sh 9086
qsub -pe localslots 6 -e /dev/null -o /dev/null /net/per900c/raid0/ledduy/github-projects/kaori-ins2014/nmduc/train_dpm_models_job.sh 9087
qsub -pe localslots 6 -e /dev/null -o /dev/null /net/per900c/raid0/ledduy/github-projects/kaori-ins2014/nmduc/train_dpm_models_job.sh 9088
qsub -pe localslots 6 -e /dev/null -o /dev/null /net/per900c/raid0/ledduy/github-projects/kaori-ins2014/nmduc/train_dpm_models_job.sh 9089
qsub -pe localslots 6 -e /dev/null -o /dev/null /net/per900c/raid0/ledduy/github-projects/kaori-ins2014/nmduc/train_dpm_models_job.sh 9090
qsub -pe localslots 6 -e /dev/null -o /dev/null /net/per900c/raid0/ledduy/github-projects/kaori-ins2014/nmduc/train_dpm_models_job.sh 9091
qsub -pe localslots 6 -e /dev/null -o /dev/null /net/per900c/raid0/ledduy/github-projects/kaori-ins2014/nmduc/train_dpm_models_job.sh 9092
qsub -pe localslots 6 -e /dev/null -o /dev/null /net/per900c/raid0/ledduy/github-projects/kaori-ins2014/nmduc/train_dpm_models_job.sh 9093
qsub -pe localslots 6 -e /dev/null -o /dev/null /net/per900c/raid0/ledduy/github-projects/kaori-ins2014/nmduc/train_dpm_models_job.sh 9094
qsub -pe localslots 6 -e /dev/null -o /dev/null /net/per900c/raid0/ledduy/github-projects/kaori-ins2014/nmduc/train_dpm_models_job.sh 9095
qsub -pe localslots 6 -e /dev/null -o /dev/null /net/per900c/raid0/ledduy/github-projects/kaori-ins2014/nmduc/train_dpm_models_job.sh 9096
qsub -pe localslots 6 -e /dev/null -o /dev/null /net/per900c/raid0/ledduy/github-projects/kaori-ins2014/nmduc/train_dpm_models_job.sh 9097
qsub -pe localslots 6 -e /dev/null -o /dev/null /net/per900c/raid0/ledduy/github-projects/kaori-ins2014/nmduc/train_dpm_models_job.sh 9098
